[project]
name = "caaos"
version = "0.2.6a9"
description = "Cerebral Autoregulation Assessment Open Source Platform"
authors = [
    {name = "fsmMLK",email = "fsmMLK@users.noreply.github.com"}
]
license = {text = "gpl"}
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
dependencies = [
    "scipy",
    "matplotlib",
    "lxml",
    "pyqt5",
    "pyqtgraph"
]

[project.urls]
Homepage = "https://github.com/CAAosPlatform/CAAos"
Issues = "https://github.com/CAAosPlatform/CAAos/issues"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0",
    "scipy",
    "matplotlib",
    "lxml",
    "pyqt5",
    "pyqtgraph"]
build-backend = "poetry.core.masonry.api"












